# Generated by Django 2.2.1 on 2019-06-04 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainsite', '0002_book_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookuser',
            name='finishDegree',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=5),
        ),
    ]
