# Generated by Django 2.2.1 on 2019-06-05 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainsite', '0003_auto_20190604_1844'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='dayWordNum',
            field=models.PositiveIntegerField(default=100),
        ),
        migrations.AddField(
            model_name='user',
            name='newWordNum',
            field=models.PositiveIntegerField(default=20),
        ),
    ]
