# Generated by Django 2.2.1 on 2019-06-05 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainsite', '0004_auto_20190605_1750'),
    ]

    operations = [
        migrations.AddField(
            model_name='worduser',
            name='reviewParameter',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
