# Generated by Django 2.2.1 on 2019-06-05 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainsite', '0005_worduser_reviewparameter'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='wordNum',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
